#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: bot-trader-group
#      auto-offset-reset: latest
#
#bot:
#  interval-ms: 10000
#  runtime-minutes: 30

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: bot-trader-group-${server.port}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


bot:
  interval-ms: 10000
  runtime-minutes: 30

#  spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#  spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#  spring.json.value.default.type: com.simulator.common.model.PriceUpdate
#  spring.json.use.type.headers: false
